### PR TITLE
Improve Translation

### PR DESCRIPTION
**Pull request by Narugakuruga**
Improve Translation for both variants of Chinese:
Text strings were dumped from in-game localization.
Convert the verbal difference between regions, so it won't confuse people

### CODE REVIEW

**Comment by GreenComfyTea** [comment]
Good call. Haven't even notice Traditional Chinese didn't use in-game values.

I want to ask to make some changes or justify yours before merging (those are just some changes that I was able to quickly visually distinguish, I don't know Chinese):
1) In Traditional Chinese `Level1` = `Lv1` and other levels seem to have a whitespace in between: `Level1` = `Lv 1`: 

image

2) In Simplified Chinese same thing: but its fully translated in-game instead of just `Lv1`:  

image

3) In both Chinese localizations `MasterRank1Star` = `大师1⭐` and other star strings have the star and the number flipped: `MasterRank1Star` = `大师⭐1`. Those are currently not used in the mod, but I will use them when I add full unicode support.  

image

4) In Traditional Chinese `None` seems that it was correct initially?

image

image

**Comment by GreenComfyTea** [comment]
In Simplified Chinese:

1. Frostfang Barioth is different:

image

2. All expedition objective are different:

image

3. Region Level seems to have a whitespace in the middle?

image

**Comment by Narugakuruga** [comment]
I have received this feedback and some stuff are relatively trivial.
I am taking a look into every aspect later

**Comment by Narugakuruga** [comment]
> In Simplified Chinese:
> 
> 1. Frostfang Barioth is different:
> 
> image
> 
> 2. All expedition objective are different:
> 
> image
> 
> 3. Region Level seems to have a whitespace in the middle?
> 
> image
> 
> 4. Languages are different:
> 
> image

1. It's merely a font difference.
2. Fixed
3. I think this is a format issue in original text.
4. I chose different term while meaning are the same

**Comment by GreenComfyTea** [comment]
> 2.Lv is commonly used in China so it would be comprehensible.
> 4. I chose different term while meaning are the same.

I would like to keep it 1 to 1 match with the in-game text. There might be non-natives who is trying to play it in chinese but don't know it well (students?), but more important dyslexic people will have hard time visually cross-referencing different text (including me).

> "None" in UI are equivalent of gathering quest.

That is true only for quests. For sessions `None` will behave as `No preference` and search for all sessions with any type.

image

> I found general type only consist of gathering quest and small monster quest? Clutch claw tutorial quest is single player only.

In-game quest filter for target doesn't even contain `None` and doesn't allow to search for gathering quests. I had to add it myself because my mod inverts filtering logic and if someone were to use the mod's filter, the game would still return gathering quests all the time, which is not a desire behavior. I utilized the existing `None` string because it seems fitting in English (since the filter is `Target` and you don't have any monster targets on gathering quests).

If you think that it doesn't really fit in Chinese (or even in English itself), I can add a separate string entry for quest target filter.

**Comment by Narugakuruga** [comment]
I have done all the fix. Would be nice of you to merge now😀

**Comment by Narugakuruga** [comment]
The none and gathering could be seperate I think. Sometimes I aim for egg quest too, just for fun haha

**Comment by GreenComfyTea** [comment]
I remembered why I didn't make `Gathering` string. It's because target id = `0` which currently is `None` returns not just gathering quests, but also expeditions.

**Comment by GreenComfyTea** [comment]
I am about to add custom font support. I haven't pushed any changes yet but you can start thinking what font you want your translation to have.

**Pull request merged**
